version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ELASTICSEARCH_USERNAME=username"
      - "ELASTICSEARCH_PASSWORD=password"
    ports:
      - "9200:9200"
    volumes:
      - ./application.yml:/usr/share/elasticsearch/config/application.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  mail-sender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail-sender
    ports:
      - "8088:8088"
    environment:
      - "KAFKA_BROKER=kafka:9092"
      - "ELASTICSEARCH_HOST=elasticsearch:9200"
    depends_on:
      - kafka
      - elasticsearch